name: Deploy to TestFlight

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: production

  testflight:
    name: Distribute to TestFlight
    type: testflight
    needs: [build_ios]
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      changelog: |
        Automated build from main branch
        Commit: ${{ github.sha }}
